基本は純正のみ
開発[vsc,fig,sourcetree]
log[WordCounter,qbserve]
keyborad[karabiner,typing Sound,loundtyper]
hardware[led,tre]
zsh[cakebrew]


使う時
開発[brave,chrome]
翻訳[itext]
開発[docker,arttype]
zsh[cakebrew]
timer
音楽[spotify]
