基本は純正のみ,blackTheme
develop[vsc,fig,sourcetree]
log[WordCounter,qbserve]
keyborad[karabiner,loundtyper]
hardware[led,tre,bit]
raycast
cheatsheet
alacritty

使う時
develop[brave,chrome]
translate[itext,mate]
develop[docker,arttype]
timer
