# standard apple only,blackTheme
develop[vsc,fig,sourcetree]
log[WordCounter,qbserve]
keyborad[karabiner,loundtyper]
hardware[led,tre,bit]
raycast
cheatsheet
alacritty

# use case 
develop[brave,chrome]
translate[itext,mate]
develop[docker,arttype]
timer
log[rescuetime]
