# standard apple only,blackTheme
develop[jetBrain,vsc,fig,sourcetree]
log[WordCounter,qbserve]
keyborad[karabiner,loundtyper]
hardware[led,tre,bit]
raycast
cheatsheet
terminal[iterm2,alacritty]

# use case 
develop[brave,chrome]
translate[itext,mate]
develop[docker,arttype]
timer
log[rescuetime]
